sonata-nfv/tng-gtk-sp

.travis.yml
controllers/requests_controller.rb
services/fetch_service.rb
services/process_request_service.rb
spec/services/fetch_nsd_service_spec.rb
spec/services/fetch_vnfd_service_spec.rb
spec/services/process_request_spec.rb

Unit tests with PostgreSQL on Travis are not working.

More changes trying to put unit tests to work on travis

---

controllers/requests_controller.rb
services/process_request_service.rb
spec/services/process_request_spec.rb

This is not yet the full fix, it's just a step towards it

Fix several small bugs around the creation of the request

---

Dockerfile
config.ru

Reverts sonata-nfv/tng-gtk-sp#257

Revert "Define DATABASE_URL"

---

controllers/requests_controller.rb

I used to use the 'env' to pass these parameters, but somehow it was not
working. So I've turned into changing the original (JSON) body before
passing it to the next module"

Update the way user name and email are extrated from the previous model

---

config.ru
controllers/requests_controller.rb
models/request.rb

Review all the service instantiation code, add pool size activerecord

---

config.ru
controllers/requests_controller.rb
models/request.rb

Reverts sonata-nfv/tng-gtk-sp#271

Revert "Review all the service instantiation code, add pool size activerecord"

---

services/process_create_slice_instance_request.rb
spec/services/process_create_slice_instance_request_spec.rb

`status` was being used wrongly, it's `nsiState`

Fix status reference in Slice Manager's response

---

db/migrate/20190425170720_add_flavour_and_mapping.rb
models/request.rb
services/process_request_service.rb

Add the necessary fields (see #260) into the request and passes them to the MANO

Get from sla manager the ns flavour corresponding to a given sla

---

services/fetch_flavour_from_sla_service.rb
services/fetch_nsd_service.rb
services/fetch_vnfds_service.rb
services/process_request_service.rb

Move helper classes into different files

Refactor service instantiation requests

---

controllers/slices_controller.rb

Increase sleeping times and number of iterations waiting for the list of

---

db/migrate/20190510091308_change_number_of_instances_to_int.rb
services/process_scale_service_instance_request.rb

Add validations for scaling in parameters (were working just for scaling

---

Gemfile

Changing pg and activerecord version

---

controllers/slices_controller.rb
services/fetch_vim_resources_messaging_service.rb

Updating the way to fetch the db record via correlation_id

---

services/create_networks_messaging_service.rb
services/delete_networks_messaging_service.rb

Fix network creation and deletion records update, after Felipe's fix on

---

controllers/requests_controller.rb

Fix bug slow /requests endpoint

---

controllers/slices_controller.rb

Increase the timer to > 1min to respect the timeout of IA-NBI

---

models/request.rb
services/process_request_service.rb

Request.create with .with_connection do

Increase (connection) checkout time from 5 to 30s and surround

---

db/migrate/20190710092421_add_params_param.rb
models/request.rb
services/process_request_service.rb

Add an extra 'params' parameter for the Gatekeeper to pass to the MANO

---

services/message_publishing_service.rb

Adding duration to instantiate and terminate requests

---

controllers/slices_controller.rb
db/migrate/20190722153431_add_wim_data.rb
models/infrastructure_request.rb
services/fetch_wim_resources_messaging_service.rb

This code has been written before summer holidays, and wrongly left
without being commited/pushed.

Add WAN-networks retrieval

---

controllers/requests_controller.rb
services/delete_wan_networks_messaging_service.rb

Fix wrong IA queue where WAN networks deconfiguration were being send
